# Generated by Django 3.2.7 on 2021-10-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211014_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='posts',
            new_name='post',
        ),
    ]
