# Generated by Django 3.2.7 on 2021-10-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211021_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post',
        ),
        migrations.AddField(
            model_name='category',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='api.Post'),
        ),
    ]
